### PR TITLE
First version of "export" is ready

### LINKED ISSUE #13: Walkthrough - Export
This issue has been created for keeping track of the writing of the __Export__ section.

- [x] Exporting models
- [x] Exporting annotations

### PR DESCRIPTION
**Pull request by HugoSchtr**
The export documentation is halfway done. I've written the "annotations export" section and I will finish as soon as possible the other half on exporting models.

The page needs proofreading, and I might have to re-do all gifs as I forgot to use the demo account.

Also: concerning my writing, is it the tone we're aiming for?

_______________

Todo left for #10 and others.

Will fix #13.

### CODE REVIEW

**Comment by HugoSchtr** [comment]
Exporting models section is now done!

**Comment by FloChiff** [comment]
Here are some typos that I noticed while reading, as well as a remark : 
- l. 30 --> the name "Images" for the tab should have an uppercase initial, as it is how it appears on the website
- l. 45 --> I think you should add that the name "Zip Import" will appear if you didn't set any specific name during the import. Otherwise, the name provided would be the one appearing.
- l. 45 --> I think it should be "_after_ the model" and not "with the model"
- l. 66 --> I think it should be either "Including or excluding" or "Include or exclude"

**Comment by HugoSchtr** [comment]
Thanks for the review, I modified the file accordingly :+1:

**Review by FloChiff — APPROVED** [review]

**Comment by alix-tz** [comment]
is the branch ready to be merged?

**Pull request merged**
