### PR TITLE
Fix/#13 review

### PR DESCRIPTION
**Pull request by alix-tz**
I tried to break down my corrections so that they are more easy to follow:
- I rephrased a few things, namely to clarify the meaning of "annotation", and used transcription in stead whenever possible
- I shortened the titles, removing redundant informations
- I added a section on accessing the former exports and the permalink because we actually often forget about it and I had just written a description of it in the page on User-related features

Regarding the syntax: 
- since I was using VSCode, I used the linter to homogenize the spaces and empty lines (but no big deal)
- I didn't change your markdown syntax, but I think it would be useful to homogenize it inside a file and overall in the whole docs/  (we can make changes in the wiki)
- as I showed you earlier, I added the syntax to render the Keys (`++key-short-name++`)
- I added titles to images with the following syntax : `[image: alt text](path/to/img "Title of the image")`. It's pretty straight-forward and will display a "infobulle" with the title when hovering on the image.

### CODE REVIEW

**Comment by alix-tz** [comment]
I removed information on the color of buttons because it might change, people might be color blind and also because it's illustrated in the Gif. This way it reduces the amount of information in the sentence.

**Comment by alix-tz** [comment]
Also, I think note admonitions should come before the GIF, it makes them more visible 🤔

**Comment by HugoSchtr** [comment]
Thanks a lot for the review! :)

**Comment by HugoSchtr** [comment]
I agree on harmonizing our markdown syntax, I'll change my `*` for `-` and `__` for `**` on the main branch for issue #13.

**Pull request merged**
